seed: 12345
feature_id: "archie"
feature_config: "config/features/archie.features.yaml"
nfeature: 1000000
nref: 50
ntgt: 50
ploidy: 2
geno_states: ["phased", "unphased"]
output_prefix: "hmm.config3"

nrep:
    train: 10
    test: 10

seq_len: 
    train: 50000
    test: 1000000

demog_id: 
    train: "HumanNeanderthal_3G21"
    test: "HumanNeanderthal_3G21"

demes: 
    train: "config/demog/HumanNeanderthal_3G21.yaml"
    test: "config/demog/HumanNeanderthal_3G21.yaml"

mut_rate: 
    train: 1.29e-8
    test: 1.29e-8

rec_rate: 
    train: 1e-8
    test: 1e-8

ref_id: 
    train: "YRI"
    test: "YRI"

tgt_id:
    train: "CEU"
    test: "CEU"

src_id: 
    train: "Nea"
    test: "Nea"

win_step: 10000
cutoff_num: 10

#sstar parameters
scenarios: ["true", "const", "ref_tgt_only"]
sstar_ms_params: {"true": {"yaml": "./config/demog/HumanNeanderthal_4G21_no_introgression.yaml", samples: [0, 0, 2, 100]},
"const": {"yaml": "./config/demog/HumanNeanderthal_4G21_constant_no_introgression.yaml", samples: [0, 0, 2, 100]},
"ref_tgt_only": {"yaml": "./config/demog/HumanNeanderthal_4G21_constant_ref_tgt_only.yaml", samples: [0, 2, 100]}}
score_seqlen: 50000

#sstar_ms_params: {'archie':{"true":{10:{"yaml": "./config/simulation/models/archie2_no_intro.yaml", samples: [0, 0, 2, 20]},
#50: {"yaml": "./config/simulation/models/archie2_no_intro.yaml", samples: [0, 0, 2, 100]}},
#"const":{10:{"yaml": "./config/simulation/models/archie2_no_intro.yaml", samples: [0, 0, 2, 20]},
#50: {"yaml": "./config/simulation/models/archie2_no_intro.yaml", samples: [0, 0, 2, 100]}},
#"ref_tgt_only":{10:{"yaml": "./config/simulation/models/archie2_ref_tgt_only.yaml", samples: [0, 2, 20]},
#50: {"yaml": "./config/simulation/models/archie2_ref_tgt_only.yaml", samples: [0, 2, 100]}}}}
