seed: 12345
feature_id: "archie"
feature_config: "config/features/archie.features.yaml"
nfeature: 1000000
nref: 50
ntgt: 50
ploidy: 2
geno_states: ["phased", "unphased"]
output_prefix: "gita.lr.archie.config5"

nrep:
    train: 10
    test: 10

seq_len: 
    train: 50000
    test: 200000000

demog_id: 
    train: "HumanNeanderthal_3G21"
    test: "ArchIE_4D19"

demes: 
    train: "config/demog/HumanNeanderthal_3G21.yaml"
    test: "config/demog/ArchIE_4D19.yaml"

mut_rate: 
    train: 1.29e-8
    test: 1.25e-8

rec_rate: 
    train: 1e-8
    test: 1e-8

ref_id: 
    train: "YRI"
    test: "Ref"

tgt_id:
    train: "CEU"
    test: "Tgt"

src_id: 
    train: "Nea"
    test: "Ghost"

win_step: 10000
cutoff_num: 20 
