seed: 12345
feature_id: "archie"
feature_config: "config/features/ArchIE.features.yaml"
nfeature: 1000000
ploidy: 2
output_prefix: "gaia.lr.archie.1m"

nref: 50
ntgt: 50
geno_states: ["phased", "unphased"]
dataset_states: ["imbalanced"]
data_states: ["unscaled"]
win_step: 10000
cutoff_num: 20

nrep:
    train: 10
    test: 10

seq_len: 
    train: 50000
    test: 200000000

demog_id: 
    train: "ArchIE_3D19"
    test: "HumanNeanderthal_3G21"

demes: 
    train: "config/demog/ArchIE_3D19.yaml"
    test: "config/demog/HumanNeanderthal_3G21.yaml"

mut_rate: 
    train: 1.25e-8
    test: 1.29e-8

rec_rate: 
    train: 1e-8
    test: 1e-8

ref_id: 
    train: "Ref"
    test: "YRI"

tgt_id:
    train: "Tgt"
    test: "CEU"

src_id: 
    train: "Ghost"
    test: "Nea"
