cluster:
        sbatch
                --nodes={resources.nodes}
                --cpus-per-task={resources.cpus}
                --mem={resources.mem_gb}G
                --time={resources.time}
                --job-name=smk-{rule}-{wildcards}
                --output={log}.out
                --exclude=node-a02,node-a08,node-a09,node-a11,node-a13,node-a18,node-a19,node-a24,node-a26,node-a27,node-a28,node-a29
                --partition={resources.partition}
                {resources.gres}
default-resources:
        - time=60
        - nodes=1
        - mem_gb=4
        - cpus=1
        - partition=basic
        - gres=''
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 180
jobs: 200
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
#use-conda: True
